# Generated by Django 3.0.4 on 2020-03-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_auto_20200323_0858'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orders',
            table='orders_tb',
        ),
        migrations.AlterModelTable(
            name='products',
            table='products_tb',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users_tb',
        ),
    ]
