# Generated by Django 3.0.4 on 2020-03-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_auto_20200323_0901'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orders',
            table='orders_table',
        ),
        migrations.AlterModelTable(
            name='products',
            table='products_table',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users_table',
        ),
    ]
